server:
  port: 8080
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false

spring:
  application:
    name: wishlist
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO