server:
  port: 8080
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false
    path: /error

spring:
  application:
    name: wishlist
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
  #            redirect-uri: http://localhost:8080/
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO