# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master", "prod" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: CI wishlist
    env:
      JDBC_DATABASE_URL: jdbc:postgresql://localhost:5432/wishlist_data
      JDBC_DATABASE_USERNAME: wishlist_user
      JDBC_DATABASE_PASSWORD: wishlist_password
    steps:
      - name: Check out repository
        uses: actions/checkout@v1

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml
